import * as fs from "fs";

export const privateKey = fs.readFileSync(
  process.env.JWT_ES256_PRIVATE_KEY_PATH || "", // generated by 'openssl ecparam -name prime256v1 -genkey -noout -out private-key.pem'
  "utf-8"
);
export const publicKey = fs.readFileSync(
  process.env.JWT_ES256_PUBLIC_KEY_PATH || "", // generated by 'openssl ec -in private-key.pem -pubout -out public-key.pem'
  "utf-8"
);
